"""add element_type and rate to cost_elements

Revision ID: d5604b6ab0b8
Revises: e2ac648836ef
Create Date: 2026-06-30 20:53:02.632576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd5604b6ab0b8'
down_revision: Union[str, None] = 'e2ac648836ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_elements', sa.Column('element_type', sa.String(length=20), nullable=False))
    op.add_column('cost_elements', sa.Column('rate', sa.Numeric(precision=8, scale=6), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cost_elements', 'rate')
    op.drop_column('cost_elements', 'element_type')
    # ### end Alembic commands ###
