"""add decision_maker required_by severity to icd_items

Revision ID: ed3f5af44ff8
Revises: d5604b6ab0b8
Create Date: 2026-06-30 21:08:34.302071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed3f5af44ff8'
down_revision: Union[str, None] = 'd5604b6ab0b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('icd_items', sa.Column('decision_maker', sa.String(length=255), nullable=True))
    op.add_column('icd_items', sa.Column('required_by', sa.Date(), nullable=True))
    op.add_column('icd_items', sa.Column('severity', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('icd_items', 'severity')
    op.drop_column('icd_items', 'required_by')
    op.drop_column('icd_items', 'decision_maker')
    # ### end Alembic commands ###
